trigger: 
 - master

pool:
   name: Self-Hosted-Agent

variables:
  - group: dev

steps: 

- task: Go@0
  displayName: "Go Get"
  inputs:
    command: 'get'
    arguments: '-d'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: Go@0
  displayName: "Go Build"
  inputs:
    command: 'build'
    workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: CopyFiles@2
  inputs:
    SourceFolder: '$(System.DefaultWorkingDirectory)'
    Contents: 'deployment.yaml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
     artifactName: drop

- task: Docker@2
  displayName: Build an image
  inputs:
    command: build
    dockerfile: '$(System.DefaultWorkingDirectory)/Dockerfile'
    buildContext: '$(System.DefaultWorkingDirectory)'
    repository: $(AWS_ECR_MAGE_URI)

- task: ECRPushImage@1
  inputs:
    awsCredentials: 'aws_service'
    regionName: $(AWS_REGION)
    imageSource: 'imagename'
    sourceImageName: $(AWS_ECR_MAGE_URI)
    sourceImageTag: $(Build.BuildId)
    pushTag: $(Build.BuildId)
    repositoryName: $(AWS_ECR_REPOSITORY_NAME)
